### ISSUE TITLE
[TOOLTIP]: descrição procedência/IPU ambígua

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/despesa#8]
A descrição que consta no tooltip da tabela ``dm-procedencia`` ou IPU pode ser confundida com a descrição da classificação 'fonte' ou outras tabelas que contém classificação da despesa (grupo/elemento/item): _"identifica a origem e a utilização dos recursos"_, vide linha 351 do [datapackage](https://github.com/dados-mg/despesa/blob/main/datapackage.json).

Os exemplos que seguem após o próprio conceito são mais significativos:
> Ex.: se os recursos são para livre utilização, se foram transferidos de outra unidade orçamentária, se são para contrapartida a convênios, etc.

**Comment by Andrelamor** [comment]
tabela de procedência no GRP Homologa:

![image](https://user-images.githubusercontent.com/52294411/109055705-49dcc100-76be-11eb-837f-e18a3253653b.png)

**Comment by silviana-faria** [comment]
@Andrelamor a descrição que consta no arquivo [despesa](https://github.com/transparencia-mg/mapa-consultas-portal-transparencia/blob/main/data/despesa.csv) do repositório mapas-consultas-portal-transparência foi inserida errada. O arquivo já foi corrigido com a descrição correta.

**Comment by Andrelamor** [comment]
* datapackage atualizado com a descrição do [de-para](https://github.com/transparencia-mg/transicao-siafi-para-grp/blob/8b401cb36d80b1f10add5ebd6f6fe5449061a92e/data/de-para-despesa.csv#L28): a partir da linha [432](https://github.com/dados-mg/despesa/blob/9d002ee87bb64458d67bd21d7398512b76a1a47f/datapackage.json#L432)
